version: '3.8'

services:
  api-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paper-analyzer-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - REDIS_URL=redis://db-redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db-postgres:5432/paper_analyzer
    depends_on:
      - db-redis
      - db-postgres

  ai-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paper-analyzer-worker
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - REDIS_URL=redis://db-redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db-postgres:5432/paper_analyzer
    depends_on:
      - db-redis
      - db-postgres

  db-postgres:
    image: postgres:15-alpine
    container_name: paper-analyzer-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paper_analyzer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-redis:
    image: redis:7-alpine
    container_name: paper-analyzer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  postgres_data:
